### DISCUSSION TITLE
Nav Arrows in between month name

### DISCUSSION THREAD

**Discussion by MariuzM** [gpbl/react-day-picker#1505] [Support] [answered]
Is there an easy way to change layout so that nav arrows be in between the month title? 
For example `< MONTH_NAME >` vs `MONTH_NAME <>`

**Comment by gpbl** [comment, marked as answer]
@MariuzM use CSS to change the position of the navigation buttons:

https://codesandbox.io/s/react-daypicker-navigation-buttons-xkzgvl?file=/src/styles.css

```css
.rdp-caption {
  display: flex;
  position: relative;
  justify-content: center;
}

.rdp-nav {
  white-space: nowrap;
  position: absolute;
  width: 100%;
  display: flex;
  justify-content: space-between;
}
```
