### DISCUSSION TITLE
Is it possible to style the weekend columns differently?

### DISCUSSION THREAD

**Discussion by MelissaHoweEmis** [gpbl/react-day-picker#1780] [Support]
Is it possible to style the weekend columns differently to the weekday? Such as a background to the column or text colour? Thank you

**Comment by gpbl** [comment]
@MelissaHoweEmis if you add a modifier [for each weekday](https://react-day-picker.js.org/api/types/DayOfWeek), you can assign to each of them a different class name, to which apply your desired style:

```tsx
<DayPicker
  // Assign a modifier for each weekday
  modifiers={{
    sunday: { dayOfWeek: [0] },
    monday: { dayOfWeek: [1] },
    tuesday: { dayOfWeek: [2] }
  }}
  // Assign a class name for each weekday-modifier
  modifiersClassNames={{
    sunday: "rdp-sunday",
    monday: "rdp-monday",
    tuesday: "rdp-tuesday"
  }}
  // Or assign an inline-style for each modifier
  modifiersStyles={{
    sunday: { background: 'red' },
  }}
/>
```

```css
.rdp-sunday  { background: rebeccapurple; color: white }
.rdp-monday  { background: darkviolet;    color: white }
.rdp-tuesday { background: hotpink;       color: white }
```

Will render:

<img width="504" alt="Screenshot 2023-05-02 at 19 55 42" src="https://user-images.githubusercontent.com/120693/235815037-c722d9c5-a5be-4364-9567-ae3c4700d79e.png">

See this Code Sandbox: https://codesandbox.io/s/react-daypicker-forked-207wbc?file=/src/App.tsx:222-1030
