### DISCUSSION TITLE
v9: navigation with centered captions

### DISCUSSION THREAD

**Discussion by ayuhito** [gpbl/react-day-picker#2306] [Support] [answered]
I've been trying to recreate the navigation chevrons with the months in between, but I haven't found a way to do it since the code is semantically very difficult to modify. As you can see in the documentation, even the examples are broken which probably indicates this is an unintended bug.

## Expected Behavior

![image](https://github.com/user-attachments/assets/4a082a54-b3f2-4d43-8ab3-aff7b1f2a73d)
`v8` Documentation

## Actual Behavior

![image](https://github.com/user-attachments/assets/80c66b99-3fb8-4730-941c-a36963fbe061)
`v9` Documentation

**Comment by berkerdemirer** [comment]
If you use tailwind to style you could do:

```
<DayPicker classNames={{
months: 'inline-flex gap-5 w-full justify-center
}} />
```

**Comment by gpbl** [comment, marked as answer]
@ayuhito thanks for trying out the new version! Yes the way the navigation works changed. Instead being rendered for each month (which was causing any sort of workaround to align the buttons), the navigation is rendered on top of the months.

You can add this CSS to restyle it:

```css
.rdp-nav {
  left: 0;
  right: 0;
}

.rdp-button_next {
  position: absolute;
  right: 0;
}

.rdp-button_prev {
  position: absolute;
  left: 0;
}

.rdp-month_caption, .rdp-caption_label {
  justify-content: center;
}
```

(not sure if it works perfectly, but you got the idea).

<img width="804" alt="Screenshot 2024-07-24 at 7 08 42 AM" src="https://github.com/user-attachments/assets/cd9ef65b-fdf4-4ab6-ab6d-4c6bd9d38f30">
