### DISCUSSION TITLE
Custom Months Navigation Component Example

### DISCUSSION THREAD

**Discussion by alessandrodias** [gpbl/react-day-picker#2404] [Ideas]
If anyone is looking for a custom months navigation example, maybe this could help.

Create the `Nav` component inside the `<DayPicker components={}` prop
```jsx
<DayPicker
  mode="range"
  pagedNavigation
  numberOfMonths={2}
  components={{
    Nav: () => {
      return (
        <nav>
          <button
            type="button"
            onClick={handlePreviousClick}
            disabled={isPreviousMonthDisabled}
          >
            previous month
          </button>

          <button type="button" onClick={handleNextClick}>
            next month
          </button>
        </nav>
      );
    },
  }}
/>
```

Then you'll have access to the `useDayPicker` hook to get the `previousMonth`, `nextMonth` and  `goToMonth` method:
```js
const { nextMonth, previousMonth, goToMonth } = useDayPicker();
```

From there, you can write your own logic to handle months navigation, or to disable navigation to previous months before the current date. Here is what I had to do in my case:
```js
// don't forget to import this to use in comparison function 
import { startOfMonth } from "date-fns";

const { nextMonth, previousMonth, goToMonth } = useDayPicker();
const [isPreviousMonthDisabled, setIsPreviousMonthDisabled] =
  useState(
    previousMonth
      ? startOfMonth(previousMonth) < startOfMonth(new Date())
      : true
  );

const handlePreviousClick = useCallback(() => {
  if (!previousMonth) return;
  goToMonth(previousMonth);
}, [previousMonth, goToMonth]);

const handleNextClick = useCallback(() => {
  if (!nextMonth) return;
  goToMonth(nextMonth);
}, [nextMonth, goToMonth]);

useEffect(() => {
  if (previousMonth) {
    setIsPreviousMonthDisabled(
      startOfMonth(previousMonth) < startOfMonth(new Date())
    );
  }
}, [previousMonth]);
```

Full Working Example:
```jsx
// imports
import { useCallback, useEffect, useState } from "react";
import { startOfMonth } from "date-fns";
import { DayPicker, useDayPicker } from "react-day-picker";

<DayPicker
  mode="range"
  pagedNavigation
  numberOfMonths={2}
  components={{
    Nav: () => {
      const { nextMonth, previousMonth, goToMonth } = useDayPicker();
      const [isPreviousMonthDisabled, setIsPreviousMonthDisabled] =
        useState(
          previousMonth
            ? startOfMonth(previousMonth) < startOfMonth(new Date())
            : true
        );

      const handlePreviousClick = useCallback(() => {
        if (!previousMonth) return;
        goToMonth(previousMonth);
      }, [previousMonth, goToMonth]);

      const handleNextClick = useCallback(() => {
        if (!nextMonth) return;
        goToMonth(nextMonth);
      }, [nextMonth, goToMonth]);

      useEffect(() => {
        if (previousMonth) {
          setIsPreviousMonthDisabled(
            startOfMonth(previousMonth) < startOfMonth(new Date())
          );
        }
      }, [previousMonth]);

      return (
        <nav>
          <button
            type="button"
            onClick={handlePreviousClick}
            disabled={isPreviousMonthDisabled}
          >
            previous month
          </button>
          <button type="button" onClick={handleNextClick}>
            next month
          </button>
        </nav>
      );
    },
  }}
/>
```

You can abstract this to another component, to improve the logic and the readability.

Hope this can help someone ✌️

**Comment by alessandrodias** [comment]
Demo:
![demo](https://github.com/user-attachments/assets/155db493-5ded-44a2-b00d-5aaabba97844)

**Comment by dalvarez** [comment]
This looks great! Question: how did you get the current 2 months to render between the nav arrows in the demo example?

**Reply by alessandrodias** [reply]
Sorry @dalvarez I missed this information in my example, but i've already updated it.

You just need to use this prop `numberOfMonths={2}` in the `<DayPicker`

Thanks for the reminder :)

**Reply by dalvarez** [reply]
Ah thanks very much for the quick response!

Also curious if you had to apply changes to the month caption to have the titles of the month to show up between the nav arrows? Ive got them rendering to the side of them based of CustomComponent for Nav

![CleanShot 2024-09-02 at 08 06 53](https://github.com/user-attachments/assets/6eb830b7-090f-42c4-a9ad-0a5ad819c467)

**Reply by alessandrodias** [reply]
@dalvarez I customized the whole styles using a separate `.css` file based on the component class names. First I tried customizing it using Tailwind, but I was having some troubles with conflicting states like `range_start` and `selected` state for example.

So I ended up creating a new css file. I'll leave it in the next comment, it case it helps you or anybody else.

**Reply by dalvarez** [reply]
Ah cheers, thanks for the help!

**Reply by gpbl** [reply]
> using Tailwind I was having some troubles with conflicting states like `range_start` and `selected` state for example.

👀 @alessandrodias , I'd like to know more about this - could you tell more about your issues with Tailwind? Thanks!

**Reply by alessandrodias** [reply]
@gpbl I was having issues were I needed to use `!` (which converts to css !important) to overwrite the styles, specially between the `selected` and `range-start`, `range-middle` and `range-end` classes.

**Comment by alessandrodias** [comment]
The css file I used to customize the Calendar styles.

Context: I was having some troubles with Tailwind and conflicting states like `range_start` and `selected` for example, so I preferred creating and importing this css file to make it ease to customize.

```css
.rdp-root {
  width: 100%;
  color: #3E3E3E;
}

.rdp-root .rdp-month_grid,
.rdp-root .rdp-month {
  display: flex;
  flex-direction: column;
  width: 100%;
}

.rdp-root .rdp-weekdays {
  display: flex;
  justify-content: space-between;
  width: 100%;
}

.rdp-root .rdp-weeks {
  display: flex;
  flex-wrap: wrap;
  width: 100%;
}

.rdp-root .rdp-week {
  display: flex;
  justify-content: space-between;
  width: 100%;
}

.rdp-root .rdp-month .rdp-month_caption {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  font-size: 12px;
  font-weight: 700;
  text-transform: capitalize;
  user-select: none;
}

.rdp-root .rdp-today:not(.rdp-outside) {
  color: #3E3E3E;
}

.rdp-root .rdp-day {
  flex: 1;
  width: auto;
  height: 32px;
  font-size: 14px;
  font-weight: 400;
}

.rdp-root .rdp-day.rdp-disabled .rdp-day_button {
  opacity: 35%;
  background-color: #FFF;
}

.rdp-root .rdp-day .rdp-day_button {
  background: #EBEBEB70;
  border-radius: 0;
  border: 0;
  width: 100%;
  height: 100%;
}

.rdp-root .rdp-day.rdp-selected .rdp-day_button,
.rdp-root .rdp-day.rdp-range_start .rdp-day_button,
.rdp-root .rdp-day.range_end .rdp-day_button {
  background-color: #19398A;
  color: #FFF;
  border: 0;
}

.rdp-root .rdp-day.rdp-range_middle .rdp-day_button {
  background: #E5ECF9 !important;
  color: #5893EC !important;
  border: 0;
}

@media (min-width: 640px) {
  .rdp-root .rdp-month_grid,
  .rdp-root .rdp-month {
    width: 240px;
  }

  .rdp-root .rdp-day {
    height: 40px;
  }
}

```
