### ISSUE TITLE
v8. Markup is broken with "showOutsideDays" and "fixedWeeks" options in December 2022

### ISSUE THREAD

**Issue by jodaka** [gpbl/react-day-picker#1207]
**Describe the bug**
Layout is broken with `"react-day-picker": "8.0.0-beta.29"` under certain conditions. 

**To Reproduce**
reproduced here: 
https://codesandbox.io/s/daypicker-basicscustomization-weeknumber-example-forked-7ej5b?file=/example.tsx
using next month button scroll to December 2022. While other months are rendered just fine, this one brakes layout

**Screenshots**
![image](https://user-images.githubusercontent.com/83644/113855575-dc39af80-97a8-11eb-8fd1-3c79a9a8d34f.png)

**Additional context**
used beta 29 (as 30 doesn't seemed to be published to npm at the moment of writing)

**Comment by roblotter** [comment]
<img width="867" alt="Screenshot 2021-05-19 at 14 29 32" src="https://user-images.githubusercontent.com/50020244/118805590-c1318380-b8ae-11eb-9299-bec8763304f6.png">

I can confirm that with the same version `8.0.0-beta.29`

I'm using `showOutsideDays=true` and `fixedWeeks=true`. You can see in the screenshot above, the row contains 14 cells for days, instead of just 7. Basically it should not try to show the next week.

**Comment by roblotter** [comment]
For now I worked around this one with the following css:

```css

    .rdp-row {
      td:nth-child(8),
      td:nth-child(9),
      td:nth-child(10),
      td:nth-child(11),
      td:nth-child(12),
      td:nth-child(13),
      td:nth-child(14) {
        display: none;
      }
    }
```

**Comment by roblotter** [comment]
Also had to add this:

```css
rdp-with_weeknumber .rdp-row td:nth-child(8) {
   display: table-cell;
}
```
to make week numbers show correctly
