### ISSUE TITLE
Unable to see .DayPicker-Day--start or --end on divs

### ISSUE THREAD

**Issue by vanessawuhoo** [gpbl/react-day-picker#1218]
**Describe the bug**
I am trying to style the start and end selected dates for a range differently than the others in the range. However, when I inspect the DatePicker using chrome dev tools, I only see `DatePicker-Day--selected` on the beginning and end dates and no `--start` or `--end` classes, so my custom styles will not apply. There does not seem to be any distinguishing elements in the classnames. 

**Expected behavior**
`.DatePicker-Day--start` and  `.DatePicker-Day--end` to be applied to the start and end of range of dates.

**Comment by razh** [comment]
Are you passing in a `modifiers` object with `start` and `end` dates?

```tsx
<DayPicker modifiers={{ start: from, end: to }} />
```

For example:

https://github.com/gpbl/react-day-picker/blob/750f6cd808b2ac29772c8df5c497a66e818080e8/docs/src/code-samples/examples/selected-range.js#L36

Do you have a reduced CodeSandbox test case?

https://github.com/gpbl/react-day-picker/blob/e60d5fa97223d300293c15d5ab6364582dacab08/.github/ISSUE_TEMPLATE/bug_report.md#L13-L14

Here's a forked version of that sandbox with the following changes:

```tsx
<DayPicker
  selectedDays={new Date()}
  modifiers={{
    start: new Date('2021-04-23'),
    end: new Date('2021-04-29'),
  }}
/>
```

```css
.DayPicker-Day--start {
  background-color: tomato;
}

.DayPicker-Day--end {
  background-color: rebeccapurple;
}
```

https://codesandbox.io/s/react-day-picker-base-forked-u73rf?file=/index.html

**Comment by vanessawuhoo** [comment]
Ahhhh! No I was not, thank you for the help! I thought they would automatically be added like --selected and missed that detail. Thanks for the thorough response!

**Comment by darkLord19** [comment]
@razh sorry to hijack this thread but in the code sandbox you have provided, when we go to next month, 29th april spot is still highlighted. I am facing similar issue. I am not able to reproduce on bare minimum daypickerinput so I am not sure what is it that's causing the issue. If you have some idea then it'd be very helpful

**Comment by razh** [comment]
@darkLord19 In the codebase I'm working on, we increase the specificity by targeting the days that can be selected. So given:

https://github.com/gpbl/react-day-picker/blob/750f6cd808b2ac29772c8df5c497a66e818080e8/src/style.css#L179-L184

We could have something like this (using Sass nesting):

```scss
.DayPicker-Day:not(.DayPicker-Day--outside) {
  &.DayPicker-Day--start {
    background-color: tomato;
  }

  &.DayPicker-Day--end {
    background-color: rebeccapurple;
  }
}
```

The `--outside` modifier refers to days outside of the current month:

https://github.com/gpbl/react-day-picker/blob/750f6cd808b2ac29772c8df5c497a66e818080e8/src/Month.js#L87
