### ISSUE TITLE
OSX: click on month change element highlights content

### ISSUE THREAD

**Issue by olegafx** [gpbl/react-day-picker#28]
OSX 10.10.3
Chrome 43.0.2357.130 (64-bit)

gif:
![react-cal](https://cloud.githubusercontent.com/assets/867546/8408149/3278d176-1e76-11e5-9aeb-0984ed0df324.gif)

**Comment by gpbl** [comment]
Hi @olegafx thanks for spotting this. are you using a trackpad? You can avoid this behavior with `user-select: none` in the css.

**Comment by olegafx** [comment]
Yes, I’m using trackpad. I saw this effect on your [demo page](http://www.gpbl.org/react-day-picker/).

**Comment by tonyspiro** [comment]
I'm still having this issue, even with `user-select` added to the CSS.  Reopen?

**Comment by gpbl** [comment]
@tonyspiro do you mean the highlight around the calendar? Or the calendar content get highlighted as well? I can't reproduce it.

**Comment by tonyspiro** [comment]
@gpbl Highlight around the calendar:
<img width="343" alt="screen shot 2016-01-08 at 3 05 59 pm" src="https://cloud.githubusercontent.com/assets/1950722/12209553/64955ec8-b619-11e5-931c-2b68057a7377.png">

**Comment by gpbl** [comment]
@tonyspiro oh that's because it is focused. When it is focused, it get the outline from the browser: this way users know they can navigate it with keyboard. 

You can remove the outline with this CSS

```css
.DayPicker:focus {
    outline: none
}
```

**Comment by tonyspiro** [comment]
Gotcha, thanks. Awesome project btw, great work!  :raised_hands:

**Comment by babenzele** [comment]
In late 2017, the above css doesn't work for me. The following does.

```css
.DayPicker-wrapper:focus {
  outline: none;
}
```

I also removed the other outlines with:

```css
.DayPicker-NavButton:focus {
  outline: none;
}
.DayPicker-Day:focus {
  outline: none;
}
```

I'm planning on adding my own styling so that keyboard-only users will still be able to navigate the calendar.
