### ISSUE TITLE
Replace navbar's CSS background with an actual SVG

### ISSUE THREAD

**Issue by catamphetamine** [gpbl/react-day-picker#708]
The "Next" and "Previous" arrows are styled using CSS SVG background.
https://github.com/gpbl/react-day-picker/blob/master/src/Navbar.js
It could be rewritten using native SVGs as children with `fill: currentColor`.
That would allow theming the date picker with:

```css
.DayPicker-NavButton
{
  color : var(--black-color);
}

.DayPicker-NavButton:active
{
  color : var(--accent-color-light);
}
```

And new properties could be added, like `navIconPrev` and `navIconNext`.
